import type { TileDef, TileType } from '@/types'

export const TILE_SIZE_PX = 16

export const TILE_KEY_MAP: Record<string, TileType> = {
	G: 'GRASS',
	D: 'DIRT',
	R: 'ROAD',
	F: 'FOREST',
	M: 'MOUNTAIN',
	W: 'WATER',
	C: 'CASTLE',
	H: 'HUT',
	S: 'CHEST',
}

export const TILE_REGISTRY: Record<TileType, TileDef> = {
	GRASS: {
		type: 'GRASS',
		symbol: '::',
		color: 'text-emerald-400',
		bg: 'bg-emerald-950/60',
		name: 'Plains',
		moveCost: 1,
		description: 'The wild terrain stretches out in all directions.',
		spriteCoords: { x: 0, y: 0 },
		encounterRate: 0.08,
	},
	DIRT: {
		type: 'DIRT',
		symbol: '·',
		color: 'text-amber-600/70',
		bg: 'bg-amber-950/30',
		name: 'Dirt Path',
		moveCost: 1,
		description: 'A well-traveled cobblestone highway.',
		spriteCoords: { x: 1, y: 0 },
		encounterRate: 0.03,
	},
	FOREST: {
		type: 'FOREST',
		symbol: '♠♠',
		color: 'text-emerald-300',
		bg: 'bg-emerald-900/80',
		name: 'Dense Forest',
		moveCost: 2,
		description: 'Towering trees block out the sun overhead.',
		spriteCoords: { x: 3, y: 0 },
		encounterRate: 0.15,
	},
	MOUNTAIN: {
		type: 'MOUNTAIN',
		symbol: '▲▲',
		color: 'text-stone-300',
		bg: 'bg-stone-800',
		name: 'High Peaks',
		moveCost: 3,
		description: 'Treacherous rocky crags loom around you.',
		spriteCoords: { x: 4, y: 0 },
		encounterRate: 0.2,
	},
	WATER: {
		type: 'WATER',
		symbol: '~~',
		color: 'text-cyan-300',
		bg: 'bg-cyan-950',
		name: 'Deep Water',
		moveCost: 99,
		description: 'Impassable rushing waters.',
		spriteCoords: { x: 5, y: 0 },
		encounterRate: 0,
	},
	ROAD: {
		type: 'ROAD',
		symbol: '==',
		color: 'text-amber-200',
		bg: 'bg-stone-900',
		name: 'Cobblestone Road',
		moveCost: 0.5,
		description: 'A well-traveled cobblestone highway.',
		spriteCoords: { x: 2, y: 0 },
		encounterRate: 0.02,
	},
	CASTLE: {
		type: 'CASTLE',
		symbol: '🏰',
		color: 'text-amber-400',
		bg: 'bg-amber-950',
		name: 'Castle Britannia',
		moveCost: 1,
		description: 'The grand gates of Castle Britannia loom before the party.',
		spriteCoords: { x: 0, y: 1 },
		encounterRate: 0,
	},
	HUT: {
		type: 'HUT',
		symbol: '🏠',
		color: 'text-amber-300',
		bg: 'bg-amber-900/60',
		name: "Iolo's Hut",
		moveCost: 1,
		description: "Iolo's wooden cottage sits quietly near the tree line.",
		spriteCoords: { x: 0, y: 2 },
		encounterRate: 0,
	},
	CHEST: {
		type: 'CHEST',
		symbol: '📦',
		color: 'text-yellow-400',
		bg: 'bg-yellow-950/80',
		name: 'Rusted Chest',
		moveCost: 1,
		description:
			'A heavy oak chest bound in tarnished iron rests in the grass.',
		spriteCoords: { x: 0, y: 3 },
		encounterRate: 0,
	},
}
