import type { TileDef, TileType } from '../types'

export const TILE_DEFS: Record<TileType, TileDef> = {
	GRASS: {
		type: 'GRASS',
		symbol: '::',
		color: 'text-emerald-400',
		bg: 'bg-emerald-950/60',
		name: 'Plains',
		moveCost: 1,
		description: 'The wild terrain stretches out in all directions.',
	},
	FOREST: {
		type: 'FOREST',
		symbol: '♠♠',
		color: 'text-emerald-300',
		bg: 'bg-emerald-900/80',
		name: 'Dense Forest',
		moveCost: 2,
		description: 'Towering trees block out the sun overhead.',
	},
	MOUNTAIN: {
		type: 'MOUNTAIN',
		symbol: '▲▲',
		color: 'text-stone-300',
		bg: 'bg-stone-800',
		name: 'High Peaks',
		moveCost: 3,
		description: 'Treacherous rocky crags loom around you.',
	},
	WATER: {
		type: 'WATER',
		symbol: '~~',
		color: 'text-cyan-300',
		bg: 'bg-cyan-950',
		name: 'Deep Water',
		moveCost: 99,
		description: 'Impassable rushing waters.',
	},
	ROAD: {
		type: 'ROAD',
		symbol: '==',
		color: 'text-amber-200',
		bg: 'bg-stone-900',
		name: 'Cobblestone Road',
		moveCost: 0.5,
		description: 'A well-traveled cobblestone highway.',
	},
	CASTLE: {
		type: 'CASTLE',
		symbol: '🏰',
		color: 'text-amber-400',
		bg: 'bg-amber-950',
		name: 'Castle Britannia',
		moveCost: 1,
		description: 'The grand gates of Castle Britannia loom before the party.',
	},
	HUT: {
		type: 'HUT',
		symbol: '🏠',
		color: 'text-amber-300',
		bg: 'bg-amber-900/60',
		name: "Iolo's Hut",
		moveCost: 1,
		description: "Iolo's wooden cottage sits quietly near the tree line.",
	},
	CHEST: {
		type: 'CHEST',
		symbol: '📦',
		color: 'text-yellow-400',
		bg: 'bg-yellow-950/80',
		name: 'Rusted Chest',
		moveCost: 1,
		description:
			'A heavy oak chest bound in tarnished iron rests in the grass.',
	},
}
